const NotificationEventType = Object.freeze({
  MESSAGE_RECEIVED: "message_received",
  SELLER_REPLIED: "seller_replied",
  BUYER_INQUIRY: "buyer_inquiry",
  MISSED_CHAT_REMINDER: "missed_chat_reminder",
  OFFER_RECEIVED: "offer_received",
  OFFER_COUNTERED: "offer_countered",
  OFFER_ACCEPTED: "offer_accepted",
  OFFER_EXPIRING: "offer_expiring",
  BUDGET_MATCH_FOUND: "budget_match_found",
  AD_APPROVED: "ad_approved",
  AD_REJECTED: "ad_rejected",
  AD_REQUIRES_CHANGES: "ad_requires_changes",
  AD_PUBLISHED: "ad_published",
  AD_EXPIRED: "ad_expired",
  AD_EXPIRING_SOON: "ad_expiring_soon",
  AD_REMOVED_BY_ADMIN: "ad_removed_by_admin",
  AD_BOOSTED: "ad_boosted",
  PAYMENT_SUCCESSFUL: "payment_successful",
  PAYMENT_FAILED: "payment_failed",
  PACKAGE_ACTIVATED: "package_activated",
  BOOST_PACKAGE_EXPIRED: "boost_package_expired",
  RENEWAL_REMINDER: "renewal_reminder",
  REFUND_INITIATED: "refund_initiated",
  REFUND_COMPLETED: "refund_completed",
  ACCOUNT_VERIFIED: "account_verified",
  SELLER_VERIFICATION_APPROVED: "seller_verification_approved",
  DOCUMENT_VERIFICATION_FAILED: "document_verification_failed",
  IDENTITY_CHECK_PENDING: "identity_check_pending",
  SUSPICIOUS_ACTIVITY_ALERT: "suspicious_activity_alert",
  PASSWORD_CHANGED: "password_changed",
  NEW_LOGIN_DETECTED: "new_login_detected",
  SAVED_SEARCH_MATCH: "saved_search_match",
  SAVED_ITEM_PRICE_DROPPED: "saved_item_price_dropped",
  FAVORITE_ITEM_UPDATED: "favorite_item_updated",
  FAVORITE_ITEM_UNAVAILABLE: "favorite_item_unavailable",
  REPORT_SUBMITTED: "report_submitted",
  REPORT_STATUS_UPDATED: "report_status_updated",
  ACCOUNT_WARNING: "account_warning",
  POLICY_VIOLATION_NOTICE: "policy_violation_notice",
  ACCOUNT_SUSPENDED: "account_suspended",
  ACCOUNT_RESTORED: "account_restored",
});

const PushNotificationEventType = NotificationEventType;
const ALL_NOTIFICATION_EVENTS = Object.values(NotificationEventType);

module.exports = {
  NotificationEventType,
  PushNotificationEventType,
  ALL_NOTIFICATION_EVENTS,
};
